#ifndef UM_GAME_AMMUNITION_TYPE_H
#define UM_GAME_AMMUNITION_TYPE_H

enum ammunition_type
{
    AMMUNITION_TYPE_NONE,

    AMMUNITION_TYPE_ARROW,
    AMMUNITION_TYPE_BOLT,
    AMMUNITION_TYPE_BULLET,
};

#endif
