#ifndef UM_GAME_ARMOR_PROFICIENCY_H
#define UM_GAME_ARMOR_PROFICIENCY_H

enum armor_proficiency
{
    ARMOR_PROFICIENCY_NONE,

    ARMOR_PROFICIENCY_HEAVY,
    ARMOR_PROFICIENCY_LIGHT,
    ARMOR_PROFICIENCY_MEDIUM,
    ARMOR_PROFICIENCY_SHIELD,

    NUM_ARMOR_PROFICIENCIES
};

#endif
