#include "assets.h"

#include <libtcod.h>

struct tile_common tile_common;
struct tile_datum tile_data[NUM_TILE_TYPES];
struct object_common object_common;
struct object_datum object_data[NUM_OBJECT_TYPES];
struct actor_common actor_common;
struct race_datum race_data[NUM_RACES];
struct class_datum class_data[NUM_CLASSES];
struct actor_prototype monster_prototypes[NUM_MONSTERS];
struct corpse_common corpse_common;
struct item_common item_common;
struct equip_slot_datum equip_slot_data[NUM_EQUIP_SLOTS];
struct item_datum item_data[NUM_ITEM_TYPES];
struct spell_datum spell_data[NUM_SPELL_TYPES];
struct projectile_datum projectile_data[NUM_PROJECTILE_TYPES];

void assets_load(void)
{
    // TODO: load from file

    tile_common.ambient_light_color = TCOD_color_RGB(16, 16, 32);
    tile_common.ambient_light_intensity = 0.05f;

    tile_data[TILE_TYPE_EMPTY] = (struct tile_datum){
        .name = "Empty",
        .glyph = ' ',
        .color = TCOD_white,
        .is_walkable = true,
        .is_transparent = true};
    tile_data[TILE_TYPE_FLOOR] = (struct tile_datum){
        .name = "Floor",
        .glyph = '.',
        .color = TCOD_white,
        .is_walkable = true,
        .is_transparent = true};
    tile_data[TILE_TYPE_GRASS] = (struct tile_datum){
        .name = "Grass",
        .glyph = '.',
        .color = TCOD_light_green,
        .is_walkable = true,
        .is_transparent = true};
    tile_data[TILE_TYPE_WALL] = (struct tile_datum){
        .name = "Wall",
        .glyph = '#',
        .color = TCOD_white,
        .is_walkable = false,
        .is_transparent = false};

    object_common.__placeholder = 0;

    object_data[OBJECT_TYPE_ALTAR] = (struct object_datum){
        .name = "Altar",
        .glyph = '_',
        .is_walkable = true,
        .is_transparent = false};
    object_data[OBJECT_TYPE_BRAZIER] = (struct object_datum){
        .name = "Brazier",
        .glyph = '*',
        .is_walkable = true,
        .is_transparent = false};
    object_data[OBJECT_TYPE_CHEST] = (struct object_datum){
        .name = "Chest",
        .glyph = '~',
        .is_walkable = true,
        .is_transparent = false};
    object_data[OBJECT_TYPE_DOOR_CLOSED] = (struct object_datum){
        .name = "Closed Door",
        .glyph = '+',
        .is_walkable = false,
        .is_transparent = false};
    object_data[OBJECT_TYPE_DOOR_OPEN] = (struct object_datum){
        .name = "Open Door",
        .glyph = '-',
        .is_walkable = true,
        .is_transparent = true};
    object_data[OBJECT_TYPE_FOUNTAIN] = (struct object_datum){
        .name = "Fountain",
        .glyph = '{',
        .is_walkable = true,
        .is_transparent = false};
    object_data[OBJECT_TYPE_STAIR_DOWN] = (struct object_datum){
        .name = "Stair Down",
        .glyph = '>',
        .is_walkable = true,
        .is_transparent = true};
    object_data[OBJECT_TYPE_STAIR_UP] = (struct object_datum){
        .name = "Stair Up",
        .glyph = '<',
        .is_walkable = true,
        .is_transparent = true};
    object_data[OBJECT_TYPE_THRONE] = (struct object_datum){
        .name = "Throne",
        .glyph = '\\',
        .is_walkable = true,
        .is_transparent = false};
    object_data[OBJECT_TYPE_TRAP] = (struct object_datum){
        .name = "Trap",
        .glyph = '^',
        .is_walkable = true,
        .is_transparent = true};

    actor_common.turns_to_chase = 10;
    actor_common.glow_radius = 5;
    actor_common.glow_color = TCOD_white;
    actor_common.glow_intensity = 0.1f;
    actor_common.torch_radius = 10;
    actor_common.torch_color = TCOD_light_amber;
    actor_common.torch_intensity = 0.25f;

    race_data[RACE_HUMAN] = (struct race_datum){
        .name = "Human",
        .glyph = '@',
        .speed = 1.0f};
    race_data[RACE_DWARF] = (struct race_datum){
        .name = "Dwarf",
        .glyph = '@',
        .speed = 0.8f};
    race_data[RACE_ELF] = (struct race_datum){
        .name = "Elf",
        .glyph = '@',
        .speed = 1.2f};

    race_data[RACE_ANIMAL] = (struct race_datum){
        .name = "Animal",
        .glyph = 'a',
        .speed = 0.9f};
    race_data[RACE_BUGBEAR] = (struct race_datum){
        .name = "Bugbear",
        .glyph = 'b',
        .speed = 0.7f};
    race_data[RACE_ORC] = (struct race_datum){
        .name = "Orc",
        .glyph = 'o',
        .speed = 0.7f};
    race_data[RACE_SLIME] = (struct race_datum){
        .name = "Slime",
        .glyph = 's',
        .speed = 0.5f};

    class_data[CLASS_WARRIOR] = (struct class_datum){
        .name = "Warrior",
        .color = TCOD_brass};
    class_data[CLASS_MAGE] = (struct class_datum){
        .name = "Wizard",
        .color = TCOD_azure};
    class_data[CLASS_ROGUE] = (struct class_datum){
        .name = "Rogue",
        .color = TCOD_yellow};

    class_data[CLASS_ANIMAL] = (struct class_datum){
        .name = "Animal",
        .color = TCOD_lightest_grey};
    class_data[CLASS_SLIME] = (struct class_datum){
        .name = "Slime",
        .color = TCOD_lightest_grey};

    monster_prototypes[MONSTER_BUGBEAR] = (struct actor_prototype){
        .name = "Bugbear",
        .race = RACE_BUGBEAR,
        .class = CLASS_WARRIOR};
    monster_prototypes[MONSTER_ORC] = (struct actor_prototype){
        .name = "Orc",
        .race = RACE_ORC,
        .class = CLASS_WARRIOR};
    monster_prototypes[MONSTER_RAT] = (struct actor_prototype){
        .name = "Rat",
        .race = RACE_ANIMAL,
        .class = CLASS_ANIMAL};
    monster_prototypes[MONSTER_SLIME] = (struct actor_prototype){
        .name = "Slime",
        .race = RACE_SLIME,
        .class = CLASS_SLIME};

    corpse_common.glyph = '%';
    corpse_common.color = TCOD_dark_red;

    item_common.__placeholder = 0;

    equip_slot_data[EQUIP_SLOT_NONE] = (struct equip_slot_datum){
        .name = "None"};
    equip_slot_data[EQUIP_SLOT_AMMUNITION] = (struct equip_slot_datum){
        .name = "Ammunition"};
    equip_slot_data[EQUIP_SLOT_ARMOR] = (struct equip_slot_datum){
        .name = "Armor"};
    equip_slot_data[EQUIP_SLOT_MAIN_HAND] = (struct equip_slot_datum){
        .name = "Main Hand"};
    equip_slot_data[EQUIP_SLOT_OFF_HAND] = (struct equip_slot_datum){
        .name = "Off Hand"};

    item_data[ITEM_TYPE_BODKIN_ARROW] = (struct item_datum){
        .name = "Bodkin Arrow",
        .description = "A sharp, wooden arrow with a pointy tip.",
        .glyph = '`',
        .color = TCOD_white,
        .equip_slot = EQUIP_SLOT_AMMUNITION,
        .two_handed = false,
        .armor = 0,
        .block_chance = 0,
        .min_damage = 1,
        .max_damage = 2,
        .ranged = false,
        .max_durability = 100,
        .quaffable = false,
        .max_stack = 100,
        .ammunition_type = AMMUNITION_TYPE_ARROW,
        .unique = false,
    };
    item_data[ITEM_TYPE_BOLT] = (struct item_datum){
        .name = "Bolt",
        .description = "Standard ammunition for a crossbow.",
        .glyph = '`',
        .color = TCOD_white,
        .equip_slot = EQUIP_SLOT_AMMUNITION,
        .two_handed = false,
        .armor = 0,
        .block_chance = 0,
        .min_damage = 2,
        .max_damage = 3,
        .ranged = false,
        .max_durability = 100,
        .quaffable = false,
        .max_stack = 100,
        .ammunition_type = AMMUNITION_TYPE_BOLT,
        .unique = false};
    item_data[ITEM_TYPE_COLD_IRON_BLADE] = (struct item_datum){
        .name = "Cold Iron Blade",
        .description = "A magical sword.",
        .glyph = '|',
        .color = TCOD_white,
        .equip_slot = EQUIP_SLOT_MAIN_HAND,
        .two_handed = false,
        .armor = 0,
        .block_chance = 0,
        .min_damage = 1,
        .max_damage = 8,
        .ranged = false,
        .max_durability = 100,
        .quaffable = false,
        .max_stack = 1,
        .ammunition_type = AMMUNITION_TYPE_NONE,
        .unique = true};
    item_data[ITEM_TYPE_CROSSBOW] = (struct item_datum){
        .name = "Crossbow",
        .description = "A powerful ranged weapon.",
        .glyph = '}',
        .color = TCOD_white,
        .equip_slot = EQUIP_SLOT_MAIN_HAND,
        .two_handed = true,
        .armor = 0,
        .block_chance = 0,
        .min_damage = 4,
        .max_damage = 12,
        .ranged = true,
        .max_durability = 100,
        .quaffable = false,
        .max_stack = 1,
        .ammunition_type = AMMUNITION_TYPE_BOLT,
        .unique = false};
    item_data[ITEM_TYPE_GOLD] = (struct item_datum){
        .name = "Gold",
        .description = "Shiny!",
        .glyph = '$',
        .color = TCOD_gold,
        .equip_slot = EQUIP_SLOT_NONE,
        .two_handed = false,
        .armor = 0,
        .block_chance = 0,
        .min_damage = 0,
        .max_damage = 0,
        .ranged = false,
        .max_durability = 0,
        .quaffable = true,
        .max_stack = INT32_MAX,
        .ammunition_type = AMMUNITION_TYPE_NONE,
        .unique = false};
    item_data[ITEM_TYPE_GREATSWORD] = (struct item_datum){
        .name = "Greatsword",
        .description = "A two-handed straight sword.",
        .glyph = '|',
        .color = TCOD_white,
        .equip_slot = EQUIP_SLOT_MAIN_HAND,
        .two_handed = true,
        .armor = 0,
        .block_chance = 0,
        .min_damage = 4,
        .max_damage = 12,
        .ranged = false,
        .max_durability = 100,
        .quaffable = false,
        .max_stack = 1,
        .ammunition_type = AMMUNITION_TYPE_NONE,
        .unique = false};
    item_data[ITEM_TYPE_HEALING_POTION] = (struct item_datum){
        .name = "Healing Potion",
        .description = "Restores full health.",
        .glyph = '!',
        .color = TCOD_red,
        .equip_slot = EQUIP_SLOT_NONE,
        .two_handed = false,
        .armor = 0,
        .block_chance = 0,
        .min_damage = 0,
        .max_damage = 0,
        .ranged = false,
        .max_durability = 0,
        .quaffable = true,
        .max_stack = 10,
        .ammunition_type = AMMUNITION_TYPE_NONE,
        .unique = false};
    item_data[ITEM_TYPE_IRON_ARMOR] = (struct item_datum){
        .name = "Iron Armor",
        .description = "A set of iron armor.",
        .glyph = '[',
        .color = TCOD_white,
        .equip_slot = EQUIP_SLOT_ARMOR,
        .two_handed = false,
        .armor = 3,
        .block_chance = 0,
        .min_damage = 0,
        .max_damage = 0,
        .ranged = false,
        .max_durability = 100,
        .quaffable = false,
        .max_stack = 1,
        .ammunition_type = AMMUNITION_TYPE_NONE,
        .unique = false};
    item_data[ITEM_TYPE_KITE_SHIELD] = (struct item_datum){
        .name = "Kite Shield",
        .description = "A medium-sized shield.",
        .glyph = ')',
        .color = TCOD_white,
        .equip_slot = EQUIP_SLOT_OFF_HAND,
        .two_handed = false,
        .armor = 0,
        .block_chance = 0.3f,
        .min_damage = 0,
        .max_damage = 0,
        .ranged = false,
        .max_durability = 100,
        .quaffable = false,
        .max_stack = 1,
        .ammunition_type = AMMUNITION_TYPE_NONE,
        .unique = false};
    item_data[ITEM_TYPE_LONGBOW] = (struct item_datum){
        .name = "Longbow",
        .description = "A tall war bow.",
        .glyph = '}',
        .color = TCOD_white,
        .equip_slot = EQUIP_SLOT_MAIN_HAND,
        .two_handed = true,
        .armor = 0,
        .block_chance = 0,
        .min_damage = 1,
        .max_damage = 8,
        .ranged = true,
        .max_durability = 100,
        .quaffable = false,
        .max_stack = 1,
        .ammunition_type = AMMUNITION_TYPE_ARROW,
        .unique = false};
    item_data[ITEM_TYPE_LONGSWORD] = (struct item_datum){
        .name = "Longsword",
        .description = "A straight sword.",
        .glyph = '|',
        .color = TCOD_white,
        .equip_slot = EQUIP_SLOT_MAIN_HAND,
        .two_handed = false,
        .armor = 0,
        .block_chance = 0,
        .min_damage = 1,
        .max_damage = 8,
        .ranged = false,
        .max_durability = 100,
        .quaffable = false,
        .max_stack = 1,
        .ammunition_type = AMMUNITION_TYPE_NONE,
        .unique = false};
    item_data[ITEM_TYPE_SCEPTER_OF_UNITY] = (struct item_datum){
        .name = "Scepter of Unity",
        .description = "A magical scepter.",
        .glyph = '!',
        .color = TCOD_white,
        .equip_slot = EQUIP_SLOT_MAIN_HAND,
        .two_handed = false,
        .armor = 0,
        .block_chance = 0,
        .min_damage = 1,
        .max_damage = 8,
        .ranged = false,
        .max_durability = 100,
        .quaffable = false,
        .max_stack = 1,
        .ammunition_type = AMMUNITION_TYPE_NONE,
        .unique = true};
    item_data[ITEM_TYPE_SPIKED_SHIELD] = (struct item_datum){
        .name = "Spiked Shield",
        .description = "A spiked shield.",
        .glyph = ')',
        .color = TCOD_white,
        .equip_slot = EQUIP_SLOT_OFF_HAND,
        .two_handed = false,
        .armor = 0,
        .block_chance = 0.3f,
        .min_damage = 1,
        .max_damage = 4,
        .ranged = false,
        .max_durability = 100,
        .quaffable = false,
        .max_stack = 1,
        .ammunition_type = AMMUNITION_TYPE_NONE,
        .unique = true};

    spell_data[SPELL_TYPE_HEAL] = (struct spell_datum){
        .name = "Heal",
        .range = SPELL_RANGE_SELF};
    spell_data[SPELL_TYPE_LIGHTNING] = (struct spell_datum){
        .name = "Lightning",
        .range = SPELL_RANGE_TARGET};
    spell_data[SPELL_TYPE_FIREBALL] = (struct spell_datum){
        .name = "Fireball",
        .range = SPELL_RANGE_TARGET};

    projectile_data[PROJECTILE_TYPE_ARROW] = (struct projectile_datum){
        .glyph = '`',
        .color = TCOD_white,
        .light_radius = -1,
        .light_color = TCOD_white,
        .light_intensity = 0.0f,
        .light_flicker = false,
        .speed = 50.0f};
    projectile_data[PROJECTILE_TYPE_FIREBALL] = (struct projectile_datum){
        .glyph = '*',
        .color = TCOD_flame,
        .light_radius = 5,
        .light_color = TCOD_flame,
        .light_intensity = 0.1f,
        .light_flicker = true,
        .speed = 30.0f};
}
