#ifndef UM_GAME_DAMAGE_TYPE_H
#define UM_GAME_DAMAGE_TYPE_H

enum damage_type
{
    DAMAGE_TYPE_NONE,

    DAMAGE_TYPE_BLUDGEONING,
    DAMAGE_TYPE_PIERCING,
    DAMAGE_TYPE_PIERCING_SLASHING,
    DAMAGE_TYPE_SLASHING,

    NUM_DAMAGE_TYPES,
};

#endif
