#ifndef UM_GAME_EQUIPPABILITY_H
#define UM_GAME_EQUIPPABILITY_H

enum equippability
{
    EQUIPPABILITY_TOO_LARGE,
    EQUIPPABILITY_BARELY,
    EQUIPPABILITY_COMFORTABLY,
    EQUIPPABILITY_EASILY,
    EQUIPPABILITY_TOO_SMALL,
};

#endif
