#ifndef UM_GAME_FACTION_H
#define UM_GAME_FACTION_H

enum faction
{
    FACTION_ADVENTURER,
    FACTION_GNOLL,
    FACTION_GOBLINOID,
    FACTION_KOBOLD,
    FACTION_MAGICAL_BEAST,
    FACTION_OUTSIDER,
    FACTION_OGRE,
    FACTION_ORC,
    FACTION_RED_DRAGON,
    FACTION_TROLL,
    FACTION_UNDEAD,
    FACTION_WILD_ANIMAL,
    FACTION_VERMIN,

    NUM_FACTIONS,
};

#endif
