#ifndef UM_GAME_FACTION_H
#define UM_GAME_FACTION_H

enum faction
{
    FACTION_ADVENTURER,
    FACTION_GNOLL,
    FACTION_GOBLINOID,
    FACTION_KOBOLD,
    FACTION_RED_DRAGON,
    FACTION_TROLL,
    FACTION_UNDEAD,
    FACTION_WILD_ANIMAL,

    NUM_FACTIONS,
};

#endif
