#ifndef UM_GAME_MONSTER_H
#define UM_GAME_MONSTER_H

enum monster
{
    MONSTER_BAT,
    MONSTER_BUGBEAR,
    MONSTER_DIRE_RAT,
    MONSTER_HYENA,
    MONSTER_GNOLL,
    MONSTER_GOBLIN,
    MONSTER_HOBGOBLIN,
    MONSTER_KOBOLD,
    MONSTER_RAT,
    MONSTER_RED_DRAGON_WYRMLING,
    MONSTER_RED_DRAGON_ADULT,
    MONSTER_RED_DRAGON_ANCIENT,
    MONSTER_TROLL,
    MONSTER_SKELETON_WARRIOR,

    NUM_MONSTERS,
};

#endif
