#ifndef UM_GAME_SPELL_H
#define UM_GAME_SPELL_H

#include <libtcod.h>

enum spell_type
{
    SPELL_TYPE_NONE,

    SPELL_TYPE_ACID_SPLASH,
    SPELL_TYPE_CURE_MINOR_WOUNDS,
    SPELL_TYPE_CURE_LIGHT_WOUNDS,
    SPELL_TYPE_CURE_MODERATE_WOUNDS,
    SPELL_TYPE_CURE_SERIOUS_WOUNDS,
    SPELL_TYPE_CURE_CRITICAL_WOUNDS,
    SPELL_TYPE_CHAIN_LIGHTNING,
    SPELL_TYPE_DAZE,
    SPELL_TYPE_FIREBALL,
    SPELL_TYPE_HARM,
    SPELL_TYPE_HEAL,
    SPELL_TYPE_INFLICT_MINOR_WOUNDS,
    SPELL_TYPE_INFLICT_LIGHT_WOUNDS,
    SPELL_TYPE_INFLICT_MODERATE_WOUNDS,
    SPELL_TYPE_INFLICT_SERIOUS_WOUNDS,
    SPELL_TYPE_INFLICT_CRITICAL_WOUNDS,
    SPELL_TYPE_MAGIC_MISSILE,
    SPELL_TYPE_RAY_OF_FROST,
    SPELL_TYPE_RESTORE_MANA,
    SPELL_TYPE_SUMMON_FAMILIAR,

    NUM_SPELL_TYPES
};

struct spell_data
{
    const char *name;
    int level;
    enum magic_type magic_type;
    enum spell_range range;
    bool harmful;
};

extern const struct spell_data spell_database[NUM_SPELL_TYPES];

#endif
