#ifndef UM_GAME_WEAPON_PROFICIENCY_H
#define UM_GAME_WEAPON_PROFICIENCY_H

enum weapon_proficiency
{
    WEAPON_PROFICIENCY_NONE,

    WEAPON_PROFICIENCY_ELF,
    WEAPON_PROFICIENCY_EXOTIC,
    WEAPON_PROFICIENCY_MARTIAL,
    WEAPON_PROFICIENCY_ROGUE,
    WEAPON_PROFICIENCY_SIMPLE,
    WEAPON_PROFICIENCY_WIZARD,

    NUM_WEAPON_PROFICIENCIES
};

#endif
