#include <roguelike/roguelike.h>

struct tile_common tile_common;
struct tile_info tile_info[NUM_TILE_TYPES];
struct object_common object_common;
struct object_info object_info[NUM_OBJECT_TYPES];
struct actor_common actor_common;
struct race_info race_info[NUM_RACES];
struct class_info class_info[NUM_CLASSES];
struct prototype monster_prototype[NUM_MONSTERS];
struct item_common item_common;
struct equip_slot_info equip_slot_info[NUM_EQUIP_SLOTS];
struct base_item_info base_item_info[NUM_BASE_ITEMS];
struct item_property_info item_property_info[NUM_ITEM_PROPERTIES];
struct item_info item_info[NUM_ITEM_TYPES];

#define TILE_COMMON(_shadow_color) tile_common.shadow_color = _shadow_color;

#define TILE_INFO(_type, _name, _glyph, _color, _is_transparent, _is_walkable) \
    tile_info[_type].name = _name;                                             \
    tile_info[_type].glyph = _glyph;                                           \
    tile_info[_type].color = _color;                                           \
    tile_info[_type].is_transparent = _is_transparent;                         \
    tile_info[_type].is_walkable = _is_walkable;

#define OBJECT_COMMON(_placeholder) \
    object_common.__placeholder = _placeholder;

#define OBJECT_INFO(_type, _name, _glyph, _is_transparent, _is_walkable) \
    object_info[_type].name = _name;                                     \
    object_info[_type].glyph = _glyph;                                   \
    object_info[_type].is_transparent = _is_transparent;                 \
    object_info[_type].is_walkable = _is_walkable;

#define ACTOR_COMMON(_turns_to_chase, _glow_radius, _glow_color, _torch_radius, _torch_color) \
    actor_common.turns_to_chase = _turns_to_chase;                                            \
    actor_common.glow_radius = _glow_radius;                                                  \
    actor_common.glow_color = _glow_color;                                                    \
    actor_common.torch_radius = _torch_radius;                                                \
    actor_common.torch_color = _torch_color;

#define RACE_INFO(_race, _name, _glyph, _size) \
    race_info[_race].name = _name;             \
    race_info[_race].glyph = _glyph;           \
    race_info[_race].size = _size;

#define CLASS_INFO(_class, _name, _color, _hit_die) \
    class_info[_class].name = _name;                \
    class_info[_class].color = _color;              \
    class_info[_class].hit_die = _hit_die;

#define MONSTER_PROTOTYPE(_monster, _name, _race, _class) \
    monster_prototype[_monster].name = _name;             \
    monster_prototype[_monster].race = _race;             \
    monster_prototype[_monster].class = _class;

#define CLASS_INFO(_class, _name, _color, _hit_die) \
    class_info[_class].name = _name;                \
    class_info[_class].color = _color;              \
    class_info[_class].hit_die = _hit_die;

#define MONSTER_PROTOTYPE(_monster, _name, _race, _class) \
    monster_prototype[_monster].name = _name;             \
    monster_prototype[_monster].race = _race;             \
    monster_prototype[_monster].class = _class;

void assets_load(void)
{
    TILE_COMMON(TCOD_color_RGB(16, 16, 32));

    TILE_INFO(TILE_TYPE_EMPTY, "Empty", ' ', TCOD_white, true, true);
    TILE_INFO(TILE_TYPE_FLOOR, "Floor", '.', TCOD_white, true, true);
    TILE_INFO(TILE_TYPE_WALL, "Wall", '#', TCOD_white, false, false);

    OBJECT_COMMON(0);

    OBJECT_INFO(OBJECT_TYPE_ALTAR, "Altar", '_', true, false);
    OBJECT_INFO(OBJECT_TYPE_BRAZIER, "Brazier", '*', true, false);
    OBJECT_INFO(OBJECT_TYPE_DOOR_CLOSED, "Closed Door", '+', false, false);
    OBJECT_INFO(OBJECT_TYPE_DOOR_OPEN, "Open Door", '-', true, true);
    OBJECT_INFO(OBJECT_TYPE_FOUNTAIN, "Fountain", '{', true, false);
    OBJECT_INFO(OBJECT_TYPE_STAIR_DOWN, "Stair Down", '>', true, true);
    OBJECT_INFO(OBJECT_TYPE_STAIR_UP, "Stair Up", '<', true, true);
    OBJECT_INFO(OBJECT_TYPE_THRONE, "Throne", '\\', true, false);

    ACTOR_COMMON(10, 5, TCOD_white, 10, TCOD_light_amber);

    RACE_INFO(RACE_DWARF, "Dwarf", '@', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_ELF, "Elf", '@', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_GNOME, "Gnome", '@', RACE_SIZE_SMALL);
    RACE_INFO(RACE_HALF_ELF, "Half-Elf", '@', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_HALF_ORC, "Half-Orc", '@', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_HALFLING, "Halfling", '@', RACE_SIZE_SMALL);
    RACE_INFO(RACE_HUMAN, "Human", '@', RACE_SIZE_MEDIUM);

    RACE_INFO(RACE_ABBERATION, "Abberation", 'A', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_ANIMAL, "Animal", 'a', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_BEAST, "Beast", 'b', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_CONSTRUCT, "Construct", 'c', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_DRAGON, "Dragon", 'D', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_ELEMENTAL, "Elemental", 'e', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_FEY, "Fey", 'f', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_GIANT, "Giant", 'G', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_GOBLINOID, "Goblinoid", 'g', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_MAGICAL_BEAST, "Magical Beast", 'M', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_MONSTROUS_HUMANOID, "Monstrous Humanoid", 'm', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_OOZE, "Ooze", 'O', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_ORC, "Orc", 'o', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_OUTSIDER, "Outsider", 'z', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_REPTILLIAN, "Reptillian", 'r', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_SHAPECHANGER, "Shapechanger", 's', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_UNDEAD, "Undead", 'u', RACE_SIZE_MEDIUM);
    RACE_INFO(RACE_VERMIN, "Vermin", 'v', RACE_SIZE_MEDIUM);

    CLASS_INFO(CLASS_BARBARIAN, "Barbarian", TCOD_amber, 12);
    CLASS_INFO(CLASS_BARD, "Bard", TCOD_purple, 6);
    CLASS_INFO(CLASS_CLERIC, "Cleric", TCOD_white, 8);
    CLASS_INFO(CLASS_DRUID, "Druid", TCOD_orange, 8);
    CLASS_INFO(CLASS_FIGHTER, "Fighter", TCOD_brass, 10);
    CLASS_INFO(CLASS_MONK, "Monk", TCOD_sea, 8);
    CLASS_INFO(CLASS_PALADIN, "Paladin", TCOD_pink, 10);
    CLASS_INFO(CLASS_RANGER, "Ranger", TCOD_green, 10);
    CLASS_INFO(CLASS_ROGUE, "Rogue", TCOD_yellow, 6);
    CLASS_INFO(CLASS_SORCERER, "Sorcerer", TCOD_flame, 4);
    CLASS_INFO(CLASS_WIZARD, "Wizard", TCOD_azure, 4);

    CLASS_INFO(CLASS_ABBERATION, "Abberation", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_ANIMAL, "Animal", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_BEAST, "Beast", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_COMMONER, "Commonder", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_CONSTRUCT, "Construct", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_DRAGON, "Dragon", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_ELEMENTAL, "Elemental", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_FEY, "Fey", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_GIANT, "Giant", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_HUMANOID, "Humanoid", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_MAGICAL_BEAST, "Magical Beast", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_MONSTROUS, "Monstrous", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_OOZE, "Ooze", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_OUTSIDER, "Outsider", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_SHAPESHIFTER, "Shapeshifter", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_UNDEAD, "Undead", TCOD_lightest_grey, 10);
    CLASS_INFO(CLASS_VERMIN, "Vermin", TCOD_lightest_grey, 10);

    MONSTER_PROTOTYPE(MONSTER_BASILISK, "Basilisk", RACE_BEAST, CLASS_BEAST);
    MONSTER_PROTOTYPE(MONSTER_BEHOLDER, "Beholder", RACE_ABBERATION, CLASS_ABBERATION);
    MONSTER_PROTOTYPE(MONSTER_BUGBEAR, "Bugbear", RACE_GOBLINOID, CLASS_HUMANOID);
    MONSTER_PROTOTYPE(MONSTER_FIRE_ELEMENTAL, "Fire Elemental", RACE_ELEMENTAL, CLASS_ELEMENTAL);
    MONSTER_PROTOTYPE(MONSTER_GELATINOUS_CUBE, "Gelatinous Cube", RACE_OOZE, CLASS_OOZE);
    MONSTER_PROTOTYPE(MONSTER_GOBLIN, "Goblin", RACE_GOBLINOID, CLASS_HUMANOID);
    MONSTER_PROTOTYPE(MONSTER_IRON_GOLEM, "Iron Golem", RACE_CONSTRUCT, CLASS_CONSTRUCT);
    MONSTER_PROTOTYPE(MONSTER_OGRE, "Ogre", RACE_GIANT, CLASS_GIANT);
    MONSTER_PROTOTYPE(MONSTER_ORC_CLERIC, "Orc Cleric", RACE_ORC, CLASS_CLERIC);
    monster_prototype[MONSTER_ORC_FIGHTER].name = "Orc Fighter";
    monster_prototype[MONSTER_ORC_FIGHTER].race = RACE_ORC;
    monster_prototype[MONSTER_ORC_FIGHTER].class = CLASS_FIGHTER;
    monster_prototype[MONSTER_ORC_RANGER].name = "Orc Ranger";
    monster_prototype[MONSTER_ORC_RANGER].race = RACE_ORC;
    monster_prototype[MONSTER_ORC_RANGER].class = CLASS_RANGER;
    monster_prototype[MONSTER_PIXIE].name = "Pixie";
    monster_prototype[MONSTER_PIXIE].race = RACE_FEY;
    monster_prototype[MONSTER_PIXIE].class = CLASS_FEY;
    monster_prototype[MONSTER_RAKSHASA].name = "Rakshasa";
    monster_prototype[MONSTER_RAKSHASA].race = RACE_REPTILLIAN;
    monster_prototype[MONSTER_RAKSHASA].class = CLASS_SHAPESHIFTER;
    monster_prototype[MONSTER_RAT].name = "Rat";
    monster_prototype[MONSTER_RAT].race = RACE_VERMIN;
    monster_prototype[MONSTER_RAT].class = CLASS_VERMIN;
    monster_prototype[MONSTER_RED_SLAAD].name = "Red Slaad";
    monster_prototype[MONSTER_RED_SLAAD].race = RACE_OUTSIDER;
    monster_prototype[MONSTER_RED_SLAAD].class = CLASS_OUTSIDER;
    monster_prototype[MONSTER_WOLF].name = "Wolf";
    monster_prototype[MONSTER_WOLF].race = RACE_ANIMAL;
    monster_prototype[MONSTER_WOLF].class = CLASS_ANIMAL;
    monster_prototype[MONSTER_WYRMLING].name = "Wyrmling";
    monster_prototype[MONSTER_WYRMLING].race = RACE_DRAGON;
    monster_prototype[MONSTER_WYRMLING].class = CLASS_DRAGON;
    monster_prototype[MONSTER_ZOMBIE].name = "Zombie";
    monster_prototype[MONSTER_ZOMBIE].race = RACE_UNDEAD;
    monster_prototype[MONSTER_ZOMBIE].class = CLASS_UNDEAD;

    item_common.__placeholder = 0;

    equip_slot_info[EQUIP_SLOT_ARMOR].name = "Armor";
    equip_slot_info[EQUIP_SLOT_ARMOR].label = "Armor ";
    equip_slot_info[EQUIP_SLOT_BELT].name = "Belt";
    equip_slot_info[EQUIP_SLOT_BELT].label = "Belt  ";
    equip_slot_info[EQUIP_SLOT_BOOTS].name = "Boots";
    equip_slot_info[EQUIP_SLOT_BOOTS].label = "Boots ";
    equip_slot_info[EQUIP_SLOT_CLOAK].name = "Cloak";
    equip_slot_info[EQUIP_SLOT_CLOAK].label = "Cloak ";
    equip_slot_info[EQUIP_SLOT_GLOVES].name = "Gloves";
    equip_slot_info[EQUIP_SLOT_GLOVES].label = "Gloves";
    equip_slot_info[EQUIP_SLOT_HELMET].name = "Helmet";
    equip_slot_info[EQUIP_SLOT_HELMET].label = "Helmet";
    equip_slot_info[EQUIP_SLOT_MAIN_HAND].name = "Main Hand";
    equip_slot_info[EQUIP_SLOT_MAIN_HAND].label = "M-Hand";
    equip_slot_info[EQUIP_SLOT_OFF_HAND].name = "Off Hand";
    equip_slot_info[EQUIP_SLOT_OFF_HAND].label = "O-Hand";

    base_item_info[BASE_ITEM_BATTLEAXE].glyph = 'T';
    base_item_info[BASE_ITEM_BATTLEAXE].color = TCOD_white;
    base_item_info[BASE_ITEM_BATTLEAXE].weight = 7;
    base_item_info[BASE_ITEM_BATTLEAXE].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_BATTLEAXE].damage = DAMAGE_SLASHING;
    base_item_info[BASE_ITEM_BATTLEAXE].weapon_size = WEAPON_SIZE_MEDIUM;
    base_item_info[BASE_ITEM_BATTLEAXE].ranged = false;
    base_item_info[BASE_ITEM_BATTLEAXE].num_dice = 1;
    base_item_info[BASE_ITEM_BATTLEAXE].die_to_roll = 8;
    base_item_info[BASE_ITEM_BATTLEAXE].crit_threat = 20;
    base_item_info[BASE_ITEM_BATTLEAXE].crit_mult = 3;
    base_item_info[BASE_ITEM_BATTLEAXE].base_cost = 10;
    base_item_info[BASE_ITEM_BATTLEAXE].stack = 1;
    base_item_info[BASE_ITEM_BATTLEAXE].base_ac = 0;
    base_item_info[BASE_ITEM_BATTLEAXE].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_BATTLEAXE].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_CLUB].glyph = '!';
    base_item_info[BASE_ITEM_CLUB].color = TCOD_white;
    base_item_info[BASE_ITEM_CLUB].weight = 1;
    base_item_info[BASE_ITEM_CLUB].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_CLUB].damage = DAMAGE_BLUDGEONING;
    base_item_info[BASE_ITEM_CLUB].weapon_size = WEAPON_SIZE_MEDIUM;
    base_item_info[BASE_ITEM_CLUB].ranged = false;
    base_item_info[BASE_ITEM_CLUB].num_dice = 1;
    base_item_info[BASE_ITEM_CLUB].die_to_roll = 6;
    base_item_info[BASE_ITEM_CLUB].crit_threat = 20;
    base_item_info[BASE_ITEM_CLUB].crit_mult = 2;
    base_item_info[BASE_ITEM_CLUB].base_cost = 3;
    base_item_info[BASE_ITEM_CLUB].stack = 1;
    base_item_info[BASE_ITEM_CLUB].base_ac = 0;
    base_item_info[BASE_ITEM_CLUB].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_CLUB].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_DAGGER].glyph = '-';
    base_item_info[BASE_ITEM_DAGGER].color = TCOD_white;
    base_item_info[BASE_ITEM_DAGGER].weight = 1;
    base_item_info[BASE_ITEM_DAGGER].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_DAGGER].damage = DAMAGE_PIERCING;
    base_item_info[BASE_ITEM_DAGGER].weapon_size = WEAPON_SIZE_TINY;
    base_item_info[BASE_ITEM_DAGGER].ranged = false;
    base_item_info[BASE_ITEM_DAGGER].num_dice = 1;
    base_item_info[BASE_ITEM_DAGGER].die_to_roll = 4;
    base_item_info[BASE_ITEM_DAGGER].crit_threat = 19;
    base_item_info[BASE_ITEM_DAGGER].crit_mult = 2;
    base_item_info[BASE_ITEM_DAGGER].base_cost = 4;
    base_item_info[BASE_ITEM_DAGGER].stack = 1;
    base_item_info[BASE_ITEM_DAGGER].base_ac = 0;
    base_item_info[BASE_ITEM_DAGGER].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_DAGGER].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_GREATAXE].glyph = 'T';
    base_item_info[BASE_ITEM_GREATAXE].color = TCOD_white;
    base_item_info[BASE_ITEM_GREATAXE].weight = 20;
    base_item_info[BASE_ITEM_GREATAXE].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_GREATAXE].damage = DAMAGE_SLASHING;
    base_item_info[BASE_ITEM_GREATAXE].weapon_size = WEAPON_SIZE_LARGE;
    base_item_info[BASE_ITEM_GREATAXE].ranged = false;
    base_item_info[BASE_ITEM_GREATAXE].num_dice = 1;
    base_item_info[BASE_ITEM_GREATAXE].die_to_roll = 12;
    base_item_info[BASE_ITEM_GREATAXE].crit_threat = 20;
    base_item_info[BASE_ITEM_GREATAXE].crit_mult = 3;
    base_item_info[BASE_ITEM_GREATAXE].base_cost = 20;
    base_item_info[BASE_ITEM_GREATAXE].stack = 1;
    base_item_info[BASE_ITEM_GREATAXE].base_ac = 0;
    base_item_info[BASE_ITEM_GREATAXE].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_GREATAXE].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_GREATSWORD].glyph = '|';
    base_item_info[BASE_ITEM_GREATSWORD].color = TCOD_white;
    base_item_info[BASE_ITEM_GREATSWORD].weight = 15;
    base_item_info[BASE_ITEM_GREATSWORD].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_GREATSWORD].damage = DAMAGE_SLASHING;
    base_item_info[BASE_ITEM_GREATSWORD].weapon_size = WEAPON_SIZE_LARGE;
    base_item_info[BASE_ITEM_GREATSWORD].ranged = false;
    base_item_info[BASE_ITEM_GREATSWORD].num_dice = 2;
    base_item_info[BASE_ITEM_GREATSWORD].die_to_roll = 6;
    base_item_info[BASE_ITEM_GREATSWORD].crit_threat = 19;
    base_item_info[BASE_ITEM_GREATSWORD].crit_mult = 2;
    base_item_info[BASE_ITEM_GREATSWORD].base_cost = 50;
    base_item_info[BASE_ITEM_GREATSWORD].stack = 1;
    base_item_info[BASE_ITEM_GREATSWORD].base_ac = 0;
    base_item_info[BASE_ITEM_GREATSWORD].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_GREATSWORD].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_HALBERD].glyph = 'P';
    base_item_info[BASE_ITEM_HALBERD].color = TCOD_white;
    base_item_info[BASE_ITEM_HALBERD].weight = 15;
    base_item_info[BASE_ITEM_HALBERD].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_HALBERD].damage = DAMAGE_PIERCING;
    base_item_info[BASE_ITEM_HALBERD].weapon_size = WEAPON_SIZE_LARGE;
    base_item_info[BASE_ITEM_HALBERD].ranged = false;
    base_item_info[BASE_ITEM_HALBERD].num_dice = 1;
    base_item_info[BASE_ITEM_HALBERD].die_to_roll = 10;
    base_item_info[BASE_ITEM_HALBERD].crit_threat = 20;
    base_item_info[BASE_ITEM_HALBERD].crit_mult = 3;
    base_item_info[BASE_ITEM_HALBERD].base_cost = 10;
    base_item_info[BASE_ITEM_HALBERD].stack = 1;
    base_item_info[BASE_ITEM_HALBERD].base_ac = 0;
    base_item_info[BASE_ITEM_HALBERD].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_HALBERD].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].glyph = 'T';
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].color = TCOD_white;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].weight = 9;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].damage = DAMAGE_PIERCING;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].weapon_size = WEAPON_SIZE_MEDIUM;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].ranged = true;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].num_dice = 1;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].die_to_roll = 10;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].crit_threat = 19;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].crit_mult = 2;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].base_cost = 50;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].stack = 1;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].base_ac = 0;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_HEAVY_CROSSBOW].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_KATANA].glyph = '(';
    base_item_info[BASE_ITEM_KATANA].color = TCOD_white;
    base_item_info[BASE_ITEM_KATANA].weight = 10;
    base_item_info[BASE_ITEM_KATANA].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_KATANA].damage = DAMAGE_SLASHING;
    base_item_info[BASE_ITEM_KATANA].weapon_size = WEAPON_SIZE_MEDIUM;
    base_item_info[BASE_ITEM_KATANA].ranged = false;
    base_item_info[BASE_ITEM_KATANA].num_dice = 1;
    base_item_info[BASE_ITEM_KATANA].die_to_roll = 10;
    base_item_info[BASE_ITEM_KATANA].crit_threat = 19;
    base_item_info[BASE_ITEM_KATANA].crit_mult = 2;
    base_item_info[BASE_ITEM_KATANA].base_cost = 40;
    base_item_info[BASE_ITEM_KATANA].stack = 1;
    base_item_info[BASE_ITEM_KATANA].base_ac = 0;
    base_item_info[BASE_ITEM_KATANA].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_KATANA].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_LARGE_SHIELD].glyph = ')';
    base_item_info[BASE_ITEM_LARGE_SHIELD].color = TCOD_white;
    base_item_info[BASE_ITEM_LARGE_SHIELD].weight = 15;
    base_item_info[BASE_ITEM_LARGE_SHIELD].equip_slot = EQUIP_SLOT_OFF_HAND;
    base_item_info[BASE_ITEM_LARGE_SHIELD].damage = 0;
    base_item_info[BASE_ITEM_LARGE_SHIELD].weapon_size = 0;
    base_item_info[BASE_ITEM_LARGE_SHIELD].ranged = false;
    base_item_info[BASE_ITEM_LARGE_SHIELD].num_dice = 0;
    base_item_info[BASE_ITEM_LARGE_SHIELD].die_to_roll = 0;
    base_item_info[BASE_ITEM_LARGE_SHIELD].crit_threat = 0;
    base_item_info[BASE_ITEM_LARGE_SHIELD].crit_mult = 0;
    base_item_info[BASE_ITEM_LARGE_SHIELD].base_cost = 50;
    base_item_info[BASE_ITEM_LARGE_SHIELD].stack = 1;
    base_item_info[BASE_ITEM_LARGE_SHIELD].base_ac = 2;
    base_item_info[BASE_ITEM_LARGE_SHIELD].armor_check_penalty = -2;
    base_item_info[BASE_ITEM_LARGE_SHIELD].arcane_spell_failure = 15;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].glyph = 'T';
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].color = TCOD_white;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].weight = 6;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].damage = DAMAGE_PIERCING;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].weapon_size = WEAPON_SIZE_SMALL;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].ranged = true;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].num_dice = 1;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].die_to_roll = 8;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].crit_threat = 19;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].crit_mult = 2;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].base_cost = 35;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].stack = 1;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].base_ac = 0;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_LIGHT_CROSSBOW].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_LONGBOW].glyph = '}';
    base_item_info[BASE_ITEM_LONGBOW].color = TCOD_white;
    base_item_info[BASE_ITEM_LONGBOW].weight = 3;
    base_item_info[BASE_ITEM_LONGBOW].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_LONGBOW].damage = DAMAGE_PIERCING;
    base_item_info[BASE_ITEM_LONGBOW].weapon_size = WEAPON_SIZE_LARGE;
    base_item_info[BASE_ITEM_LONGBOW].ranged = true;
    base_item_info[BASE_ITEM_LONGBOW].num_dice = 1;
    base_item_info[BASE_ITEM_LONGBOW].die_to_roll = 8;
    base_item_info[BASE_ITEM_LONGBOW].crit_threat = 20;
    base_item_info[BASE_ITEM_LONGBOW].crit_mult = 3;
    base_item_info[BASE_ITEM_LONGBOW].base_cost = 75;
    base_item_info[BASE_ITEM_LONGBOW].stack = 1;
    base_item_info[BASE_ITEM_LONGBOW].base_ac = 0;
    base_item_info[BASE_ITEM_LONGBOW].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_LONGBOW].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_LONGSWORD].glyph = '|';
    base_item_info[BASE_ITEM_LONGSWORD].color = TCOD_white;
    base_item_info[BASE_ITEM_LONGSWORD].weight = 4;
    base_item_info[BASE_ITEM_LONGSWORD].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_LONGSWORD].damage = DAMAGE_SLASHING;
    base_item_info[BASE_ITEM_LONGSWORD].weapon_size = WEAPON_SIZE_MEDIUM;
    base_item_info[BASE_ITEM_LONGSWORD].ranged = false;
    base_item_info[BASE_ITEM_LONGSWORD].num_dice = 1;
    base_item_info[BASE_ITEM_LONGSWORD].die_to_roll = 8;
    base_item_info[BASE_ITEM_LONGSWORD].crit_threat = 19;
    base_item_info[BASE_ITEM_LONGSWORD].crit_mult = 2;
    base_item_info[BASE_ITEM_LONGSWORD].base_cost = 15;
    base_item_info[BASE_ITEM_LONGSWORD].stack = 1;
    base_item_info[BASE_ITEM_LONGSWORD].base_ac = 0;
    base_item_info[BASE_ITEM_LONGSWORD].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_LONGSWORD].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_MACE].glyph = '!';
    base_item_info[BASE_ITEM_MACE].color = TCOD_white;
    base_item_info[BASE_ITEM_MACE].weight = 6;
    base_item_info[BASE_ITEM_MACE].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_MACE].damage = DAMAGE_BLUDGEONING;
    base_item_info[BASE_ITEM_MACE].weapon_size = WEAPON_SIZE_SMALL;
    base_item_info[BASE_ITEM_MACE].ranged = false;
    base_item_info[BASE_ITEM_MACE].num_dice = 1;
    base_item_info[BASE_ITEM_MACE].die_to_roll = 6;
    base_item_info[BASE_ITEM_MACE].crit_threat = 19;
    base_item_info[BASE_ITEM_MACE].crit_mult = 2;
    base_item_info[BASE_ITEM_MACE].base_cost = 5;
    base_item_info[BASE_ITEM_MACE].stack = 1;
    base_item_info[BASE_ITEM_MACE].base_ac = 0;
    base_item_info[BASE_ITEM_MACE].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_MACE].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_POTION].glyph = '!';
    base_item_info[BASE_ITEM_POTION].color = TCOD_white;
    base_item_info[BASE_ITEM_POTION].weight = 0.5f;
    base_item_info[BASE_ITEM_POTION].equip_slot = EQUIP_SLOT_NONE;
    base_item_info[BASE_ITEM_POTION].damage = 0;
    base_item_info[BASE_ITEM_POTION].weapon_size = 0;
    base_item_info[BASE_ITEM_POTION].ranged = false;
    base_item_info[BASE_ITEM_POTION].num_dice = 0;
    base_item_info[BASE_ITEM_POTION].die_to_roll = 0;
    base_item_info[BASE_ITEM_POTION].crit_threat = 0;
    base_item_info[BASE_ITEM_POTION].crit_mult = 0;
    base_item_info[BASE_ITEM_POTION].base_cost = 30;
    base_item_info[BASE_ITEM_POTION].stack = 10;
    base_item_info[BASE_ITEM_POTION].base_ac = 0;
    base_item_info[BASE_ITEM_POTION].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_POTION].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_QUARTERSTAFF].glyph = '|';
    base_item_info[BASE_ITEM_QUARTERSTAFF].color = TCOD_white;
    base_item_info[BASE_ITEM_QUARTERSTAFF].weight = 4;
    base_item_info[BASE_ITEM_QUARTERSTAFF].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_QUARTERSTAFF].damage = DAMAGE_BLUDGEONING;
    base_item_info[BASE_ITEM_QUARTERSTAFF].weapon_size = WEAPON_SIZE_LARGE;
    base_item_info[BASE_ITEM_QUARTERSTAFF].ranged = false;
    base_item_info[BASE_ITEM_QUARTERSTAFF].num_dice = 1;
    base_item_info[BASE_ITEM_QUARTERSTAFF].die_to_roll = 6;
    base_item_info[BASE_ITEM_QUARTERSTAFF].crit_threat = 20;
    base_item_info[BASE_ITEM_QUARTERSTAFF].crit_mult = 2;
    base_item_info[BASE_ITEM_QUARTERSTAFF].base_cost = 1;
    base_item_info[BASE_ITEM_QUARTERSTAFF].stack = 1;
    base_item_info[BASE_ITEM_QUARTERSTAFF].base_ac = 0;
    base_item_info[BASE_ITEM_QUARTERSTAFF].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_QUARTERSTAFF].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_SCIMITAR].glyph = '|';
    base_item_info[BASE_ITEM_SCIMITAR].color = TCOD_white;
    base_item_info[BASE_ITEM_SCIMITAR].weight = 4;
    base_item_info[BASE_ITEM_SCIMITAR].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_SCIMITAR].damage = DAMAGE_SLASHING;
    base_item_info[BASE_ITEM_SCIMITAR].weapon_size = WEAPON_SIZE_MEDIUM;
    base_item_info[BASE_ITEM_SCIMITAR].ranged = false;
    base_item_info[BASE_ITEM_SCIMITAR].num_dice = 1;
    base_item_info[BASE_ITEM_SCIMITAR].die_to_roll = 6;
    base_item_info[BASE_ITEM_SCIMITAR].crit_threat = 18;
    base_item_info[BASE_ITEM_SCIMITAR].crit_mult = 2;
    base_item_info[BASE_ITEM_SCIMITAR].base_cost = 15;
    base_item_info[BASE_ITEM_SCIMITAR].stack = 1;
    base_item_info[BASE_ITEM_SCIMITAR].base_ac = 0;
    base_item_info[BASE_ITEM_SCIMITAR].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_SCIMITAR].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_SHORTBOW].glyph = '}';
    base_item_info[BASE_ITEM_SHORTBOW].color = TCOD_white;
    base_item_info[BASE_ITEM_SHORTBOW].weight = 2;
    base_item_info[BASE_ITEM_SHORTBOW].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_SHORTBOW].damage = DAMAGE_PIERCING;
    base_item_info[BASE_ITEM_SHORTBOW].weapon_size = WEAPON_SIZE_MEDIUM;
    base_item_info[BASE_ITEM_SHORTBOW].ranged = true;
    base_item_info[BASE_ITEM_SHORTBOW].num_dice = 1;
    base_item_info[BASE_ITEM_SHORTBOW].die_to_roll = 6;
    base_item_info[BASE_ITEM_SHORTBOW].crit_threat = 20;
    base_item_info[BASE_ITEM_SHORTBOW].crit_mult = 3;
    base_item_info[BASE_ITEM_SHORTBOW].base_cost = 30;
    base_item_info[BASE_ITEM_SHORTBOW].stack = 1;
    base_item_info[BASE_ITEM_SHORTBOW].base_ac = 0;
    base_item_info[BASE_ITEM_SHORTBOW].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_SHORTBOW].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_SHORTSWORD].glyph = '-';
    base_item_info[BASE_ITEM_SHORTSWORD].color = TCOD_white;
    base_item_info[BASE_ITEM_SHORTSWORD].weight = 3;
    base_item_info[BASE_ITEM_SHORTSWORD].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_SHORTSWORD].damage = DAMAGE_PIERCING;
    base_item_info[BASE_ITEM_SHORTSWORD].weapon_size = WEAPON_SIZE_SMALL;
    base_item_info[BASE_ITEM_SHORTSWORD].ranged = false;
    base_item_info[BASE_ITEM_SHORTSWORD].num_dice = 1;
    base_item_info[BASE_ITEM_SHORTSWORD].die_to_roll = 6;
    base_item_info[BASE_ITEM_SHORTSWORD].crit_threat = 19;
    base_item_info[BASE_ITEM_SHORTSWORD].crit_mult = 2;
    base_item_info[BASE_ITEM_SHORTSWORD].base_cost = 10;
    base_item_info[BASE_ITEM_SHORTSWORD].stack = 1;
    base_item_info[BASE_ITEM_SHORTSWORD].base_ac = 0;
    base_item_info[BASE_ITEM_SHORTSWORD].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_SHORTSWORD].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_SMALL_SHIELD].glyph = ')';
    base_item_info[BASE_ITEM_SMALL_SHIELD].color = TCOD_white;
    base_item_info[BASE_ITEM_SMALL_SHIELD].weight = 6;
    base_item_info[BASE_ITEM_SMALL_SHIELD].equip_slot = EQUIP_SLOT_OFF_HAND;
    base_item_info[BASE_ITEM_SMALL_SHIELD].damage = 0;
    base_item_info[BASE_ITEM_SMALL_SHIELD].weapon_size = 0;
    base_item_info[BASE_ITEM_SMALL_SHIELD].ranged = false;
    base_item_info[BASE_ITEM_SMALL_SHIELD].num_dice = 0;
    base_item_info[BASE_ITEM_SMALL_SHIELD].die_to_roll = 0;
    base_item_info[BASE_ITEM_SMALL_SHIELD].crit_threat = 0;
    base_item_info[BASE_ITEM_SMALL_SHIELD].crit_mult = 0;
    base_item_info[BASE_ITEM_SMALL_SHIELD].base_cost = 9;
    base_item_info[BASE_ITEM_SMALL_SHIELD].stack = 1;
    base_item_info[BASE_ITEM_SMALL_SHIELD].base_ac = 1;
    base_item_info[BASE_ITEM_SMALL_SHIELD].armor_check_penalty = -1;
    base_item_info[BASE_ITEM_SMALL_SHIELD].arcane_spell_failure = 5;
    base_item_info[BASE_ITEM_SPEAR].glyph = '/';
    base_item_info[BASE_ITEM_SPEAR].color = TCOD_white;
    base_item_info[BASE_ITEM_SPEAR].weight = 3;
    base_item_info[BASE_ITEM_SPEAR].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_SPEAR].damage = DAMAGE_PIERCING;
    base_item_info[BASE_ITEM_SPEAR].weapon_size = WEAPON_SIZE_LARGE;
    base_item_info[BASE_ITEM_SPEAR].ranged = false;
    base_item_info[BASE_ITEM_SPEAR].num_dice = 1;
    base_item_info[BASE_ITEM_SPEAR].die_to_roll = 8;
    base_item_info[BASE_ITEM_SPEAR].crit_threat = 20;
    base_item_info[BASE_ITEM_SPEAR].crit_mult = 3;
    base_item_info[BASE_ITEM_SPEAR].base_cost = 1;
    base_item_info[BASE_ITEM_SPEAR].stack = 1;
    base_item_info[BASE_ITEM_SPEAR].base_ac = 0;
    base_item_info[BASE_ITEM_SPEAR].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_SPEAR].arcane_spell_failure = 0;
    base_item_info[BASE_ITEM_TOWER_SHIELD].glyph = ')';
    base_item_info[BASE_ITEM_TOWER_SHIELD].color = TCOD_white;
    base_item_info[BASE_ITEM_TOWER_SHIELD].weight = 45;
    base_item_info[BASE_ITEM_TOWER_SHIELD].equip_slot = EQUIP_SLOT_OFF_HAND;
    base_item_info[BASE_ITEM_TOWER_SHIELD].damage = 0;
    base_item_info[BASE_ITEM_TOWER_SHIELD].weapon_size = 0;
    base_item_info[BASE_ITEM_TOWER_SHIELD].ranged = false;
    base_item_info[BASE_ITEM_TOWER_SHIELD].num_dice = 0;
    base_item_info[BASE_ITEM_TOWER_SHIELD].die_to_roll = 0;
    base_item_info[BASE_ITEM_TOWER_SHIELD].crit_threat = 0;
    base_item_info[BASE_ITEM_TOWER_SHIELD].crit_mult = 0;
    base_item_info[BASE_ITEM_TOWER_SHIELD].base_cost = 100;
    base_item_info[BASE_ITEM_TOWER_SHIELD].stack = 1;
    base_item_info[BASE_ITEM_TOWER_SHIELD].base_ac = 3;
    base_item_info[BASE_ITEM_TOWER_SHIELD].armor_check_penalty = -10;
    base_item_info[BASE_ITEM_TOWER_SHIELD].arcane_spell_failure = 50;
    base_item_info[BASE_ITEM_WARHAMMER].glyph = '!';
    base_item_info[BASE_ITEM_WARHAMMER].color = TCOD_white;
    base_item_info[BASE_ITEM_WARHAMMER].weight = 8;
    base_item_info[BASE_ITEM_WARHAMMER].equip_slot = EQUIP_SLOT_MAIN_HAND;
    base_item_info[BASE_ITEM_WARHAMMER].damage = DAMAGE_BLUDGEONING;
    base_item_info[BASE_ITEM_WARHAMMER].weapon_size = WEAPON_SIZE_MEDIUM;
    base_item_info[BASE_ITEM_WARHAMMER].ranged = false;
    base_item_info[BASE_ITEM_WARHAMMER].num_dice = 1;
    base_item_info[BASE_ITEM_WARHAMMER].die_to_roll = 8;
    base_item_info[BASE_ITEM_WARHAMMER].crit_threat = 20;
    base_item_info[BASE_ITEM_WARHAMMER].crit_mult = 3;
    base_item_info[BASE_ITEM_WARHAMMER].base_cost = 12;
    base_item_info[BASE_ITEM_WARHAMMER].stack = 1;
    base_item_info[BASE_ITEM_WARHAMMER].base_ac = 0;
    base_item_info[BASE_ITEM_WARHAMMER].armor_check_penalty = 0;
    base_item_info[BASE_ITEM_WARHAMMER].arcane_spell_failure = 0;

    item_property_info[ITEM_PROPERTY_AC_SHIELD_1].text = "Armor Bonus: +1 (AC Shield Modifier)";
    item_property_info[ITEM_PROPERTY_AC_SHIELD_1].enhancement_bonus = 0;
    item_property_info[ITEM_PROPERTY_AC_SHIELD_1].ac = AC_SHIELD;
    item_property_info[ITEM_PROPERTY_AC_SHIELD_1].ac_bonus = 1;
    item_property_info[ITEM_PROPERTY_ENHANCEMENT_BONUS_1].text = "Enhancement Bonus: +1";
    item_property_info[ITEM_PROPERTY_ENHANCEMENT_BONUS_1].enhancement_bonus = 1;
    item_property_info[ITEM_PROPERTY_ENHANCEMENT_BONUS_1].ac = 0;
    item_property_info[ITEM_PROPERTY_ENHANCEMENT_BONUS_1].ac_bonus = 0;

    item_info[ITEM_TYPE_BATTLEAXE].base_item = BASE_ITEM_BATTLEAXE;
    item_info[ITEM_TYPE_BATTLEAXE].name = "Battleaxe";
    item_info[ITEM_TYPE_BATTLEAXE].description = "A generic battleaxe.";
    item_info[ITEM_TYPE_BATTLEAXE_1].base_item = BASE_ITEM_BATTLEAXE;
    item_info[ITEM_TYPE_BATTLEAXE_1].name = "Battleaxe + 1";
    item_info[ITEM_TYPE_BATTLEAXE_1].description = "A special battleaxe.";
    item_info[ITEM_TYPE_BATTLEAXE_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_CLUB].base_item = BASE_ITEM_CLUB;
    item_info[ITEM_TYPE_CLUB].name = "Club";
    item_info[ITEM_TYPE_CLUB].description = "A generic club.";
    item_info[ITEM_TYPE_CLUB_1].base_item = BASE_ITEM_CLUB;
    item_info[ITEM_TYPE_CLUB_1].name = "Club + 1";
    item_info[ITEM_TYPE_CLUB_1].description = "A special club.";
    item_info[ITEM_TYPE_CLUB_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_DAGGER].base_item = BASE_ITEM_DAGGER;
    item_info[ITEM_TYPE_DAGGER].name = "Dagger";
    item_info[ITEM_TYPE_DAGGER].description = "A generic dagger.";
    item_info[ITEM_TYPE_DAGGER_1].base_item = BASE_ITEM_DAGGER;
    item_info[ITEM_TYPE_DAGGER_1].name = "Dagger + 1";
    item_info[ITEM_TYPE_DAGGER_1].description = "A special dagger.";
    item_info[ITEM_TYPE_DAGGER_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_GREATAXE].base_item = BASE_ITEM_GREATAXE;
    item_info[ITEM_TYPE_GREATAXE].name = "Greataxe";
    item_info[ITEM_TYPE_GREATAXE].description = "A generic greataxe.";
    item_info[ITEM_TYPE_GREATAXE_1].base_item = BASE_ITEM_GREATAXE;
    item_info[ITEM_TYPE_GREATAXE_1].name = "Greataxe + 1";
    item_info[ITEM_TYPE_GREATAXE_1].description = "A special greataxe.";
    item_info[ITEM_TYPE_GREATAXE_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_GREATSWORD].base_item = BASE_ITEM_GREATSWORD;
    item_info[ITEM_TYPE_GREATSWORD].name = "Greatsword";
    item_info[ITEM_TYPE_GREATSWORD].description = "A generic greatsword.";
    item_info[ITEM_TYPE_GREATSWORD_1].base_item = BASE_ITEM_GREATSWORD;
    item_info[ITEM_TYPE_GREATSWORD_1].name = "Greatsword + 1";
    item_info[ITEM_TYPE_GREATSWORD_1].description = "A special greatsword.";
    item_info[ITEM_TYPE_GREATSWORD_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_HALBERD].base_item = BASE_ITEM_HALBERD;
    item_info[ITEM_TYPE_HALBERD].name = "Halberd";
    item_info[ITEM_TYPE_HALBERD].description = "A generic halberd.";
    item_info[ITEM_TYPE_HALBERD_1].base_item = BASE_ITEM_HALBERD;
    item_info[ITEM_TYPE_HALBERD_1].name = "Halberd + 1";
    item_info[ITEM_TYPE_HALBERD_1].description = "A special halberd.";
    item_info[ITEM_TYPE_HALBERD_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_HEAVY_CROSSBOW].base_item = BASE_ITEM_HEAVY_CROSSBOW;
    item_info[ITEM_TYPE_HEAVY_CROSSBOW].name = "Heavy Crossbow";
    item_info[ITEM_TYPE_HEAVY_CROSSBOW].description = "A generic heavy crossbow.";
    item_info[ITEM_TYPE_HEAVY_CROSSBOW_1].base_item = BASE_ITEM_HEAVY_CROSSBOW;
    item_info[ITEM_TYPE_HEAVY_CROSSBOW_1].name = "Heavy Crossbow + 1";
    item_info[ITEM_TYPE_HEAVY_CROSSBOW_1].description = "A special heavy crossbow.";
    item_info[ITEM_TYPE_HEAVY_CROSSBOW_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_KATANA].base_item = BASE_ITEM_KATANA;
    item_info[ITEM_TYPE_KATANA].name = "Katana";
    item_info[ITEM_TYPE_KATANA].description = "A generic katana.";
    item_info[ITEM_TYPE_KATANA_1].base_item = BASE_ITEM_KATANA;
    item_info[ITEM_TYPE_KATANA_1].name = "Katana + 1";
    item_info[ITEM_TYPE_KATANA_1].description = "A special katana.";
    item_info[ITEM_TYPE_KATANA_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_LARGE_SHIELD].base_item = BASE_ITEM_LARGE_SHIELD;
    item_info[ITEM_TYPE_LARGE_SHIELD].name = "Large Shield";
    item_info[ITEM_TYPE_LARGE_SHIELD].description = "A generic large shield.";
    item_info[ITEM_TYPE_LARGE_SHIELD_1].base_item = BASE_ITEM_LARGE_SHIELD;
    item_info[ITEM_TYPE_LARGE_SHIELD_1].name = "Large Shield + 1";
    item_info[ITEM_TYPE_LARGE_SHIELD_1].description = "A special large shield.";
    item_info[ITEM_TYPE_LARGE_SHIELD_1].item_properties[ITEM_PROPERTY_AC_SHIELD_1] = true;
    item_info[ITEM_TYPE_LIGHT_CROSSBOW].base_item = BASE_ITEM_LIGHT_CROSSBOW;
    item_info[ITEM_TYPE_LIGHT_CROSSBOW].name = "Light Crossbow";
    item_info[ITEM_TYPE_LIGHT_CROSSBOW].description = "A generic light crossbow.";
    item_info[ITEM_TYPE_LIGHT_CROSSBOW_1].base_item = BASE_ITEM_LIGHT_CROSSBOW;
    item_info[ITEM_TYPE_LIGHT_CROSSBOW_1].name = "Light Crossbow + 1";
    item_info[ITEM_TYPE_LIGHT_CROSSBOW_1].description = "A special light crossbow.";
    item_info[ITEM_TYPE_LIGHT_CROSSBOW_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_LONGBOW].base_item = BASE_ITEM_LONGBOW;
    item_info[ITEM_TYPE_LONGBOW].name = "Longbow";
    item_info[ITEM_TYPE_LONGBOW].description = "A generic longbow.";
    item_info[ITEM_TYPE_LONGBOW_1].base_item = BASE_ITEM_LONGBOW;
    item_info[ITEM_TYPE_LONGBOW_1].name = "Longbow + 1";
    item_info[ITEM_TYPE_LONGBOW_1].description = "A special longbow.";
    item_info[ITEM_TYPE_LONGBOW_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_LONGSWORD].base_item = BASE_ITEM_LONGSWORD;
    item_info[ITEM_TYPE_LONGSWORD].name = "Longsword";
    item_info[ITEM_TYPE_LONGSWORD].description = "A generic longsword.";
    item_info[ITEM_TYPE_LONGSWORD_1].base_item = BASE_ITEM_LONGSWORD;
    item_info[ITEM_TYPE_LONGSWORD_1].name = "Longsword + 1";
    item_info[ITEM_TYPE_LONGSWORD_1].description = "A special longsword.";
    item_info[ITEM_TYPE_LONGSWORD_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_MACE].base_item = BASE_ITEM_MACE;
    item_info[ITEM_TYPE_MACE].name = "Mace";
    item_info[ITEM_TYPE_MACE].description = "A generic mace.";
    item_info[ITEM_TYPE_MACE_1].base_item = BASE_ITEM_MACE;
    item_info[ITEM_TYPE_MACE_1].name = "Mace + 1";
    item_info[ITEM_TYPE_MACE_1].description = "A special mace.";
    item_info[ITEM_TYPE_MACE_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_POTION_CURE_LIGHT_WOUNDS].base_item = BASE_ITEM_POTION;
    item_info[ITEM_TYPE_POTION_CURE_LIGHT_WOUNDS].name = "Potion of Cure Light Wounds";
    item_info[ITEM_TYPE_POTION_CURE_LIGHT_WOUNDS].description = "A healing potion.";
    item_info[ITEM_TYPE_QUARTERSTAFF].base_item = BASE_ITEM_QUARTERSTAFF;
    item_info[ITEM_TYPE_QUARTERSTAFF].name = "Quarterstaff";
    item_info[ITEM_TYPE_QUARTERSTAFF].description = "A generic quarterstaff.";
    item_info[ITEM_TYPE_QUARTERSTAFF_1].base_item = BASE_ITEM_QUARTERSTAFF;
    item_info[ITEM_TYPE_QUARTERSTAFF_1].name = "Quarterstaff + 1";
    item_info[ITEM_TYPE_QUARTERSTAFF_1].description = "A special quarterstaff.";
    item_info[ITEM_TYPE_QUARTERSTAFF_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_SCIMITAR].base_item = BASE_ITEM_SCIMITAR;
    item_info[ITEM_TYPE_SCIMITAR].name = "Scimitar";
    item_info[ITEM_TYPE_SCIMITAR].description = "A generic scimitar.";
    item_info[ITEM_TYPE_SCIMITAR_1].base_item = BASE_ITEM_SCIMITAR;
    item_info[ITEM_TYPE_SCIMITAR_1].name = "Scimitar + 1";
    item_info[ITEM_TYPE_SCIMITAR_1].description = "A special scimitar.";
    item_info[ITEM_TYPE_SCIMITAR_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_SHORTBOW].base_item = BASE_ITEM_SHORTBOW;
    item_info[ITEM_TYPE_SHORTBOW].name = "Shortbow";
    item_info[ITEM_TYPE_SHORTBOW].description = "A generic shortbow.";
    item_info[ITEM_TYPE_SHORTBOW_1].base_item = BASE_ITEM_SHORTBOW;
    item_info[ITEM_TYPE_SHORTBOW_1].name = "Shortbow + 1";
    item_info[ITEM_TYPE_SHORTBOW_1].description = "A special shortbow.";
    item_info[ITEM_TYPE_SHORTBOW_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_SHORTSWORD].base_item = BASE_ITEM_SHORTSWORD;
    item_info[ITEM_TYPE_SHORTSWORD].name = "Shortsword";
    item_info[ITEM_TYPE_SHORTSWORD].description = "A generic shortsword.";
    item_info[ITEM_TYPE_SHORTSWORD_1].base_item = BASE_ITEM_SHORTSWORD;
    item_info[ITEM_TYPE_SHORTSWORD_1].name = "Shortsword + 1";
    item_info[ITEM_TYPE_SHORTSWORD_1].description = "A special shortsword.";
    item_info[ITEM_TYPE_SHORTSWORD_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_SMALL_SHIELD].base_item = BASE_ITEM_SMALL_SHIELD;
    item_info[ITEM_TYPE_SMALL_SHIELD].name = "Small Shield";
    item_info[ITEM_TYPE_SMALL_SHIELD].description = "A generic small shield.";
    item_info[ITEM_TYPE_SMALL_SHIELD_1].base_item = BASE_ITEM_SMALL_SHIELD;
    item_info[ITEM_TYPE_SMALL_SHIELD_1].name = "Small Shield + 1";
    item_info[ITEM_TYPE_SMALL_SHIELD_1].description = "A special small shield.";
    item_info[ITEM_TYPE_SMALL_SHIELD_1].item_properties[ITEM_PROPERTY_AC_SHIELD_1] = true;
    item_info[ITEM_TYPE_SPEAR].base_item = BASE_ITEM_SPEAR;
    item_info[ITEM_TYPE_SPEAR].name = "Spear";
    item_info[ITEM_TYPE_SPEAR].description = "A generic spear.";
    item_info[ITEM_TYPE_SPEAR_1].base_item = BASE_ITEM_SPEAR;
    item_info[ITEM_TYPE_SPEAR_1].name = "Spear + 1";
    item_info[ITEM_TYPE_SPEAR_1].description = "A special spear.";
    item_info[ITEM_TYPE_SPEAR_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
    item_info[ITEM_TYPE_TOWER_SHIELD].base_item = BASE_ITEM_TOWER_SHIELD;
    item_info[ITEM_TYPE_TOWER_SHIELD].name = "Tower Shield";
    item_info[ITEM_TYPE_TOWER_SHIELD].description = "A generic tower shield.";
    item_info[ITEM_TYPE_TOWER_SHIELD_1].base_item = BASE_ITEM_TOWER_SHIELD;
    item_info[ITEM_TYPE_TOWER_SHIELD_1].name = "Tower Shield + 1";
    item_info[ITEM_TYPE_TOWER_SHIELD_1].description = "A special tower shield.";
    item_info[ITEM_TYPE_TOWER_SHIELD_1].item_properties[ITEM_PROPERTY_AC_SHIELD_1] = true;
    item_info[ITEM_TYPE_WARHAMMER].base_item = BASE_ITEM_WARHAMMER;
    item_info[ITEM_TYPE_WARHAMMER].name = "Warhammer";
    item_info[ITEM_TYPE_WARHAMMER].description = "A generic warhammer.";
    item_info[ITEM_TYPE_WARHAMMER_1].base_item = BASE_ITEM_WARHAMMER;
    item_info[ITEM_TYPE_WARHAMMER_1].name = "Warhammer + 1";
    item_info[ITEM_TYPE_WARHAMMER_1].description = "A special warhammer.";
    item_info[ITEM_TYPE_WARHAMMER_1].item_properties[ITEM_PROPERTY_ENHANCEMENT_BONUS_1] = true;
}
