#ifndef SCENES_GAME_AUTOMOVE_ACTION_H
#define SCENES_GAME_AUTOMOVE_ACTION_H

enum automove_action
{
    AUTOMOVE_ACTION_NONE,

    AUTOMOVE_ACTION_ATTACK,
    AUTOMOVE_ACTION_BASH,
    AUTOMOVE_ACTION_INTERACT,
    AUTOMOVE_ACTION_MOVE,
    AUTOMOVE_ACTION_SWAP,
};

#endif
