#ifndef UM_SCENES_GAME_CHARACTER_ACTION_H
#define UM_SCENES_GAME_CHARACTER_ACTION_H

enum character_action
{
    CHARACTER_ACTION_NONE,

    CHARACTER_ACTION_ABILITY_SPEND_POINT,
    CHARACTER_ACTION_EQUIPMENT_EXAMINE,
    CHARACTER_ACTION_EQUIPMENT_UNEQUIP
};

#endif
