#ifndef UM_SCENES_GAME_DIRECTIONAL_ACTION_H
#define UM_SCENES_GAME_DIRECTIONAL_ACTION_H

#include <stdbool.h>

enum direction;

enum directional_action
{
    DIRECTIONAL_ACTION_NONE,

    DIRECTIONAL_ACTION_CLOSE_DOOR,
    DIRECTIONAL_ACTION_DIP,
    DIRECTIONAL_ACTION_OPEN_DOOR,
};

#endif
