#ifndef SCENES_GAME_DIRECTIONAL_ACTION_H
#define SCENES_GAME_DIRECTIONAL_ACTION_H

#include <stdbool.h>

enum direction;

enum directional_action
{
    DIRECTIONAL_ACTION_NONE,
    DIRECTIONAL_ACTION_CLOSE_DOOR,
    DIRECTIONAL_ACTION_DRINK,
    DIRECTIONAL_ACTION_OPEN_CHEST,
    DIRECTIONAL_ACTION_OPEN_DOOR,
    DIRECTIONAL_ACTION_PRAY,
    DIRECTIONAL_ACTION_SIT
};

#endif
