#ifndef UM_SCENES_GAME_INVENTORY_ACTION_H
#define UM_SCENES_GAME_INVENTORY_ACTION_H

enum inventory_action
{
    INVENTORY_ACTION_NONE,

    INVENTORY_ACTION_DROP,
    INVENTORY_ACTION_EQUIP,
    INVENTORY_ACTION_EXAMINE,
    INVENTORY_ACTION_LEARN,
    INVENTORY_ACTION_QUAFF,
    INVENTORY_ACTION_READ,
};

#endif
