#ifndef SCENES_GAME_TARGETING_ACTION_H
#define SCENES_GAME_TARGETING_ACTION_H

enum targeting_action
{
    TARGETING_ACTION_NONE,

    TARGETING_ACTION_LOOK,
    TARGETING_ACTION_EXAMINE,
    TARGETING_ACTION_READ,
    TARGETING_ACTION_SHOOT,
    TARGETING_ACTION_SPELL
};

#endif
